FROM python:3.12-slim

WORKDIR /app

# Copiar archivos de dependencias
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copiar el resto del código
COPY . .

# El comando de inicio lo maneja Render en el render.yaml, así que no necesitas CMD aquí